use strict;
use warnings;
use Test::More;
use atspi;
no warnings 'redefine';
my (@keys, $active, $code, $wait);
($active, $code, $wait) = (1, 0, 0);
local *atspi::result = sub { return {status => 'passed', active => $active, pid => 42}; };
local *atspi::select_console = sub {};
local *atspi::send_key = sub { push @keys, $_[0]; };
local *atspi::run_command = sub { return $wait; };
local *atspi::_read_exit_code = sub { return $code; };
local *atspi::_kill_process_groups = sub { die 'unexpected forced close'; };
my $path = '/tmp/openqa-gui-status-1-2';
my $closed = atspi->close_with_shortcut(42, $path, 42, 15);
is_deeply(\@keys, ['alt-f4'], 'one standard close shortcut and no internal actions');
ok($closed->{graceful_exit}, 'normal process exit observed');
is($closed->{raw_application_exit_code}, 0, 'returns supervisor exit status');
$code = 139;
ok(atspi->close_with_shortcut(42, $path, 42, 15)->{application_crashed}, 'segfault is diagnosed');
$wait = 1;
ok(!atspi->close_with_shortcut(42, $path, 42, 15)->{graceful_exit}, 'running process is not graceful exit');
$active = 0; @keys = ();
eval { atspi->close_with_shortcut(42, $path, 42, 15) };
like($@, qr/inactive/, 'inactive application cannot be closed blindly');
is(scalar @keys, 0, 'no shortcut sent to an unrelated window');
eval { atspi->close_with_shortcut(42, $path, 42, 15, 'bad-key') };
like($@, qr/invalid close shortcut/, 'shortcut is validated');
done_testing;
